import 'dart:io';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/constants/bedrock_constants.dart';
import '../ui_components/foundation_widgets.dart';
import '../../domain/enums/domain_enums.dart';
import '../../domain/models/domain_models.dart';
import '../../core/providers/hazard_feed_provider.dart';
import '../../core/providers/location_provider.dart';
import '../../core/providers/user_profile_provider.dart';
import '../../core/services/image_picker_service.dart';
import '../../core/theme/bedrock_theme.dart';

class HazardReportScreen extends StatefulWidget {
  const HazardReportScreen({super.key});

  @override
  State<HazardReportScreen> createState() => _HazardReportScreenState();
}

class _HazardReportScreenState extends State<HazardReportScreen> {
  final _formKey = GlobalKey<FormState>();
  final _descController = TextEditingController();
  HazardType _selectedType = HazardType.accident;
  bool _isLoading = false;

  final ImagePickerService _imagePickerService = ImagePickerService();
  String? _localImagePath;

  void _pickImage() async {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(BedrockConstants.radiusLarge),
        ),
      ),
      builder: (context) {
        return Container(
          padding: const EdgeInsets.all(24),
          color: BedrockTheme.surfaceDark,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                'Select Photo Source',
                style: Theme.of(context).textTheme.headlineSmall,
              ),
              const SizedBox(height: 16),
              ListTile(
                leading: const Icon(Icons.photo_library_rounded),
                title: const Text('Gallery'),
                onTap: () async {
                  Navigator.pop(context);
                  final path = await _imagePickerService.pickImageFromGallery();
                  if (path != null) {
                    setState(() => _localImagePath = path);
                  }
                },
              ),
              ListTile(
                leading: const Icon(Icons.camera_alt_rounded),
                title: const Text('Camera'),
                onTap: () async {
                  Navigator.pop(context);
                  final path = await _imagePickerService.pickImageFromCamera();
                  if (path != null) {
                    setState(() => _localImagePath = path);
                  }
                },
              ),
            ],
          ),
        );
      },
    );
  }

  // Displays a popup warning modal requesting user action verification.
  // Reference: https://api.flutter.dev/flutter/material/AlertDialog-class.html
  void _showSubmitDialog() {
    showDialog(
      context: context,
      builder: (context) {
        // AlertDialog restricts interaction outside its bounds until dismissed.
        return AlertDialog(
          title: const Text('Confirm Report Submission'),
          content: Text(
            'Are you sure you want to report this ${_selectedType.displayName} hazard in Abbottabad?',
          ),
          actions: [
            TextButton(
              onPressed: () =>
                  Navigator.pop(context), // Dismiss dialog, returns null.
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context); // Close dialog
                _submitReport();
              },
              child: const Text('Submit'),
            ),
          ],
        );
      },
    );
  }

  void _submitReport() async {
    final locationProvider = Provider.of<LocationProvider>(
      context,
      listen: false,
    );
    final profileProvider = Provider.of<UserProfileProvider>(
      context,
      listen: false,
    );
    final feedProvider = Provider.of<HazardFeedProvider>(
      context,
      listen: false,
    );

    setState(() => _isLoading = true);

    final newHazard = HazardDisplayModel(
      id: '', // Will be generated by Firestore
      type: _selectedType,
      description: _descController.text.trim(),
      upvotes: 1, // Auto-upvoted by reporter
      downvotes: 0,
      trustScore: 1.0,
      reporterName: profileProvider.profile?.username ?? 'Anonymous',
      reporterTier: profileProvider.profile?.tier ?? ReputationTier.rookie,
      reportedAt: DateTime.now(),
      latitude: locationProvider.latitude,
      longitude: locationProvider.longitude,
      distanceMeters: 0.0,
      currentUserVote: VoteState.upvoted,
      isOwnReport: true,
    );

    final success = await feedProvider.submitReport(
      newHazard,
      localImagePath: _localImagePath,
    );

    if (mounted) {
      setState(() => _isLoading = false);
      if (success) {
        Navigator.of(context).pop('new_report_submitted');
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              feedProvider.errorMessage ?? 'Failed to submit report.',
            ),
            backgroundColor: Colors.redAccent,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    }
  }

  @override
  void dispose() {
    _descController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Report Hazard'),
        backgroundColor: Theme.of(context).colorScheme.surface,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(BedrockConstants.space24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'What is the hazard type?',
                style: Theme.of(context).textTheme.titleLarge,
              ),
              const SizedBox(height: BedrockConstants.space12),

              // Dropdown Button (rubric item)
              DropdownButtonFormField<HazardType>(
                value: _selectedType,
                decoration: InputDecoration(
                  filled: true,
                  fillColor: Theme.of(context).colorScheme.secondary,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(
                      BedrockConstants.radiusMedium,
                    ),
                    borderSide: BorderSide.none,
                  ),
                ),
                items: HazardType.values.map((type) {
                  return DropdownMenuItem<HazardType>(
                    value: type,
                    child: Text('${type.emoji} ${type.displayName}'),
                  );
                }).toList(),
                onChanged: (val) {
                  if (val != null) {
                    setState(() {
                      _selectedType = val;
                    });
                  }
                },
              ),

              const SizedBox(height: BedrockConstants.space24),
              Text(
                'Description',
                style: Theme.of(context).textTheme.titleLarge,
              ),
              const SizedBox(height: BedrockConstants.space12),
              TextFormField(
                controller: _descController,
                maxLines: 4,
                validator: (v) {
                  if (v == null || v.trim().length < 5) {
                    return 'Please provide at least 5 characters of context.';
                  }
                  return null;
                },
                decoration: InputDecoration(
                  hintText: 'Provide details to help verify this report...',
                  filled: true,
                  fillColor: Theme.of(context).colorScheme.secondary,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(
                      BedrockConstants.radiusMedium,
                    ),
                    borderSide: BorderSide.none,
                  ),
                ),
              ),
              const SizedBox(height: BedrockConstants.space24),
              Text(
                'Attach Photo Evidence (Optional)',
                style: Theme.of(context).textTheme.titleMedium,
              ),
              const SizedBox(height: BedrockConstants.space12),
              if (_localImagePath != null) ...[
                Stack(
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(
                        BedrockConstants.radiusMedium,
                      ),
                      child: Image.file(
                        File(_localImagePath!),
                        height: 180,
                        width: double.infinity,
                        fit: BoxFit.cover,
                      ),
                    ),
                    Positioned(
                      top: 8,
                      right: 8,
                      child: GestureDetector(
                        onTap: () => setState(() => _localImagePath = null),
                        child: Container(
                          padding: const EdgeInsets.all(4),
                          decoration: const BoxDecoration(
                            shape: BoxShape.circle,
                            color: Colors.black54,
                          ),
                          child: const Icon(
                            Icons.close,
                            color: Colors.white,
                            size: 20,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ] else ...[
                GestureDetector(
                  onTap: _pickImage,
                  child: Container(
                    height: 100,
                    decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.secondary,
                      borderRadius: BorderRadius.circular(
                        BedrockConstants.radiusMedium,
                      ),
                      border: Border.all(
                        color: BedrockTheme.borderSubtle.withOpacity(0.3),
                        style: BorderStyle.solid,
                      ),
                    ),
                    child: const Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(
                            Icons.add_a_photo_rounded,
                            color: Colors.white60,
                          ),
                          SizedBox(height: 8),
                          Text(
                            'Add photo evidence',
                            style: TextStyle(
                              color: Colors.white60,
                              fontSize: 13,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
              const SizedBox(height: BedrockConstants.space32),

              BedrockPrimaryButton(
                text: 'Submit Report',
                isLoading: _isLoading,
                onPressed: () {
                  if (_formKey.currentState?.validate() ?? false) {
                    _showSubmitDialog(); // Show dialog (rubric item)
                  }
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
