// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlikpHKgpm9I9wJz-nh57UrD3pswgeB4Q',
    appId: '1:853251225782:web:161c1259639124ca2ace17',
    messagingSenderId: '853251225782',
    projectId: 'bedrock-weather-app',
    authDomain: 'bedrock-weather-app.firebaseapp.com',
    storageBucket: 'bedrock-weather-app.firebasestorage.app',
    measurementId: 'G-7493ML9XT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIbwwxRjtNFmkAlsbUOwMzX0b9hme2dNc',
    appId: '1:853251225782:android:266f9548831630b62ace17',
    messagingSenderId: '853251225782',
    projectId: 'bedrock-weather-app',
    storageBucket: 'bedrock-weather-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIB_bcB_DtGQPhkZiShV7RWAN6nZJyCIQ',
    appId: '1:853251225782:ios:480788a0932fcc732ace17',
    messagingSenderId: '853251225782',
    projectId: 'bedrock-weather-app',
    storageBucket: 'bedrock-weather-app.firebasestorage.app',
    iosBundleId: 'com.abbottabad.bedrock.bedrockPhase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIB_bcB_DtGQPhkZiShV7RWAN6nZJyCIQ',
    appId: '1:853251225782:ios:480788a0932fcc732ace17',
    messagingSenderId: '853251225782',
    projectId: 'bedrock-weather-app',
    storageBucket: 'bedrock-weather-app.firebasestorage.app',
    iosBundleId: 'com.abbottabad.bedrock.bedrockPhase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlikpHKgpm9I9wJz-nh57UrD3pswgeB4Q',
    appId: '1:853251225782:web:3a9078d080192b372ace17',
    messagingSenderId: '853251225782',
    projectId: 'bedrock-weather-app',
    authDomain: 'bedrock-weather-app.firebaseapp.com',
    storageBucket: 'bedrock-weather-app.firebasestorage.app',
    measurementId: 'G-NRMT3829CY',
  );
}
